server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}
    username: ${MYSQL_ADDON_USER}
    password: ${MYSQL_ADDON_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 🔧 HikariCP Connection Pool Settings
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000         # 30 seconds
      max-lifetime: 60000         # 1 minute
      connection-timeout: 30000   # 30 seconds
      initialization-fail-timeout: 0
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  web:
    cors:
      allowed-origins: "*"
